name: Matrix Test

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'test'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.inputs.job == 'test'}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
          - ubuntu-18.04
        channel:
          - latest/stable
          - 4.0/stable
    steps:
      - uses: actions/checkout@v3
      - name: Run ${{ github.repository }}@${{ github.sha }}
        uses: ./
        with:
          channel: ${{ matrix.channel }}
      - name: Launch instance
        run: lxc launch ubuntu:focal instance
      - name: Check network connectivity
        run: |
          sleep 20  # wait to attach ip address
          lxc exec instance -- dig google.com +short
