name: Test Release

on:
  push:
  pull_request:

jobs:

  test-build:
    name: Test Setup LXD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: antyung88/gh-actions-lxd@v2.1
        with:
          channel: latest/stable
      - run: |
          lxc launch ubuntu:20.04 test1
